---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-engine
  namespace: ai-services
  labels:
    app: ai-engine
    part-of: tribe
    tier: data-processing
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ai-engine
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: ai-engine
        part-of: tribe
        tier: data-processing
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8000"
        prometheus.io/path: "/metrics"
    spec:
      containers:
      - name: ai-engine
        image: ${ECR_REPOSITORY_URI}/tribe/ai-engine:${IMAGE_TAG}
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
          name: http
        env:
        - name: AI_ENGINE_ENV
          value: "${ENVIRONMENT}"
        - name: AI_ENGINE_LOG_LEVEL
          value: "info"
        - name: PORT
          value: "8000"
        - name: OPENROUTER_API_KEY
          valueFrom:
            secretKeyRef:
              name: ai-engine-secrets
              key: openrouter-api-key
        - name: DEFAULT_AI_MODEL
          value: "openai/gpt-4"
        - name: AI_MODEL_TIMEOUT
          value: "30"
        - name: AI_CACHE_ENABLED
          value: "true"
        - name: REDIS_URL
          valueFrom:
            secretKeyRef:
              name: redis-credentials
              key: ai-engine-url
        - name: MIN_TRIBE_SIZE
          value: "4"
        - name: MAX_TRIBE_SIZE
          value: "8"
        - name: COMPATIBILITY_THRESHOLD
          value: "0.7"
        - name: MAX_TRIBES_PER_USER
          value: "3"
        envFrom:
        - configMapRef:
            name: ai-engine-config
        resources:
          requests:
            cpu: "1.0"
            memory: "1Gi"
          limits:
            cpu: "2.0"
            memory: "2Gi"
        livenessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 30
          periodSeconds: 15
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 2
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          runAsUser: 1000
          runAsGroup: 1000
          capabilities:
            drop:
            - ALL
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - ai-engine
              topologyKey: kubernetes.io/hostname
      terminationGracePeriodSeconds: 60
---
apiVersion: v1
kind: Service
metadata:
  name: ai-engine
  namespace: ai-services
  labels:
    app: ai-engine
    part-of: tribe
    tier: data-processing
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: ai-engine
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: ai-engine
  namespace: ai-services
  labels:
    app: ai-engine
    part-of: tribe
    tier: data-processing
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ai-engine
  minReplicas: 2
  maxReplicas: 6
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 60
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
      - type: Percent
        value: 100
        periodSeconds: 60
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 10
        periodSeconds: 60
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: ai-engine-pdb
  namespace: ai-services
  labels:
    app: ai-engine
    part-of: tribe
    tier: data-processing
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: ai-engine