# Kubernetes deployment configuration for the Tribe platform's Matching Service
# This service implements AI-powered matchmaking algorithms to create compatible Tribes
# based on personality profiles, shared interests, and communication styles.

---
# Deployment: Manages the matching service pods
apiVersion: apps/v1
kind: Deployment
metadata:
  name: matching-service
  namespace: api-services
  labels:
    app: matching-service
    part-of: tribe
    tier: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: matching-service
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0  # Zero-downtime deployments
  template:
    metadata:
      labels:
        app: matching-service
        part-of: tribe
        tier: backend
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "3004"
        prometheus.io/path: "/metrics"
    spec:
      containers:
      - name: matching-service
        image: ${ECR_REPOSITORY_URI}/tribe/matching-service:${IMAGE_TAG}
        imagePullPolicy: Always
        ports:
        - containerPort: 3004
          name: http
        env:
        - name: NODE_ENV
          value: "${ENVIRONMENT}"
        - name: PORT
          value: "3004"
        - name: LOG_LEVEL
          value: "info"
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: database-credentials
              key: matching-service-url
        - name: REDIS_URL
          valueFrom:
            secretKeyRef:
              name: redis-credentials
              key: url
        - name: OPENROUTER_API_KEY
          valueFrom:
            secretKeyRef:
              name: ai-credentials
              key: openrouter-api-key
        envFrom:
        - configMapRef:
            name: matching-service-config
        - secretRef:
            name: matching-service-secrets
        resources:
          requests:
            cpu: "500m"
            memory: "512Mi"
          limits:
            cpu: "1"
            memory: "1Gi"
        livenessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 30
          periodSeconds: 15
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 2
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          runAsUser: 1000
          runAsGroup: 1000
          capabilities:
            drop:
            - ALL
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - matching-service
              topologyKey: kubernetes.io/hostname
      terminationGracePeriodSeconds: 60

---
# Service: Exposes the matching service within the cluster
apiVersion: v1
kind: Service
metadata:
  name: matching-service
  namespace: api-services
  labels:
    app: matching-service
    part-of: tribe
    tier: backend
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: matching-service

---
# HorizontalPodAutoscaler: Automatically scales the matching service based on CPU utilization
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: matching-service
  namespace: api-services
  labels:
    app: matching-service
    part-of: tribe
    tier: backend
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: matching-service
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
      - type: Percent
        value: 100
        periodSeconds: 60
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 10
        periodSeconds: 60

---
# PodDisruptionBudget: Ensures high availability during voluntary disruptions
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: matching-service-pdb
  namespace: api-services
  labels:
    app: matching-service
    part-of: tribe
    tier: backend
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: matching-service