---
# Deployment for the Notification Service
# Handles push notifications, emails, and in-app alerts for the Tribe platform
apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
  namespace: api-services
  labels:
    app: notification-service
    part-of: tribe
    tier: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: notification-service
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: notification-service
        part-of: tribe
        tier: backend
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "3007"
        prometheus.io/path: "/metrics"
    spec:
      containers:
      - name: notification-service
        image: ${ECR_REPOSITORY_URI}/tribe/notification-service:${IMAGE_TAG}
        imagePullPolicy: Always
        ports:
        - containerPort: 3007
          name: http
        env:
        - name: NODE_ENV
          value: "${ENVIRONMENT}"
        - name: PORT
          value: "3007"
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: database-credentials
              key: notification-service-url
        - name: REDIS_URL
          valueFrom:
            secretKeyRef:
              name: redis-credentials
              key: url
        envFrom:
        - configMapRef:
            name: notification-service-config
        - secretRef:
            name: notification-service-secrets
        - secretRef:
            name: fcm-credentials
        resources:
          requests:
            cpu: 500m
            memory: 512Mi
          limits:
            cpu: 1
            memory: 1Gi
        livenessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 30
          periodSeconds: 15
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 2
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          runAsUser: 1000
          runAsGroup: 1000
          capabilities:
            drop:
            - ALL
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - notification-service
              topologyKey: kubernetes.io/hostname
      terminationGracePeriodSeconds: 60

---
# Service for the Notification Service
# Exposes the service within the cluster
apiVersion: v1
kind: Service
metadata:
  name: notification-service
  namespace: api-services
  labels:
    app: notification-service
    part-of: tribe
    tier: backend
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: notification-service

---
# HorizontalPodAutoscaler for the Notification Service
# Automatically scales pods based on CPU utilization to meet demand
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: notification-service
  namespace: api-services
  labels:
    app: notification-service
    part-of: tribe
    tier: backend
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: notification-service
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
      - type: Percent
        value: 100
        periodSeconds: 60
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 10
        periodSeconds: 60

---
# PodDisruptionBudget for the Notification Service
# Ensures high availability during voluntary disruptions like node maintenance
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: notification-service-pdb
  namespace: api-services
  labels:
    app: notification-service
    part-of: tribe
    tier: backend
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: notification-service